class MusicGenre {
  static final List<String> musicGenres = [
    "Select song genre",
    "Country",
    "Hip hop",
    "Rock",
    "Blues",
    "Children",
    "Christian",
    "Classic",
    "Dance",
    "Electronic",
    "Experimental",
    "Folk",
    "Funk",
    "Hard Rock",
    "Heavy Metal",
    "Indie Rock",
    "Instrumental",
    "Jazz",
    "Jingle",
    "Latin",
    "Metal",
    "Pop",
    "Reggae",
    "Soundtrack",
  ];
}
