class MusicGenre {
  static final List<String> musicGenres = [
    "Select song genre",
    "Adult contemporary music",
    "Alternative country",
    "Alternative hip hop",
    "Alternative rock",
    "Beach Music",
    "Blues",
    "Children's music",
    "Christian/Gospel",
    "Classic music",
    "Contemporary Christian music",
    "Country music",
    "Dance music",
    "Easy listening",
    "Electronic dance music",
    "Electronic music",
    "Experimental music",
    "Folk music",
    "Funk",
    "Hard rock",
    "Heavy Metal",
    "Hip hop music",
    "Indie rock",
    "Instrumental",
    "J-pop",
    "Japanese rock",
    "Jazz",
    "Jingle",
    "Latin alternative",
    "Latin music",
    "Metal, Musical theater",
    "New-age music",
    "Pop",
    "Popular music",
    "Post-disco",
    "Progressive rock",
    "Psychedelic rock",
    "Reggae",
    "Rhythm and blues",
    "Rock",
    "Singing",
    "Soul music",
    "Soundtrack",
    "Vocal music"
  ];
}
